<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaXamlCompiler>true</AvaloniaXamlCompiler>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <OptimizationPreference>Size</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <RetainVM>false</RetainVM>
    <EventSourceSupport Condition="'$(Configuration)' == 'Release'">false</EventSourceSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport"
                      Version="2.2.3"
                      Condition="'$(Configuration)' == 'Debug'" />
    <AvaloniaResource Include="assets/**" />
  </ItemGroup>
</Project>
