[package]
name = "bacom"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.11.0"
postcard = { version = "1.0", features = ["alloc"] }
egui = "=0.33.3"
eframe = "=0.33.3"
keyring = { version = "4.1.6", features = ["apple-native-keyring-store", "linux-keyutils-keyring-store"] }
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
zeroize = { version = "1.9.0", features = ["aarch64", "derive", "std"] }
egui-thematic = "0.1.1"
robius-authentication = "0.3.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
